name: Python

on:
- push

jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - run: ./scripts/download-test-data.sh
    #   env:
    #     SAS: ${{ secrets.AZURE_SAS }}

    # - run: ./requirements.test.txt
    # - run: python3 -m pip install deepspeed

    # - run: python3 scripts/read-pt.py data/global_step5/*
