name: Go

on:
- push
- pull_request

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - run: make
